# Exported from Render on 2025-03-20T17:46:24Z
services:
- type: web
  name: TM-Project-Backend
  runtime: python
  repo: https://github.com/Griffin250/TM-Project
  plan: free
  region: frankfurt
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app
version: "1"
